export const SET_URL = "SET_URL";
export const SET_COUNT = "SET_COUNT";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_RECENT_VISIBILITY = "SET_RECENT_VISIBILITY";
export const SET_RECENT_LIST = "SET_RECENT_LIST";
export const PUSH_TO_RECENT_LIST = "PUSH_TO_RECENT_LIST";
